use_frameworks!

target 'SampleFramework_Example' do
  pod 'SampleFramework', :path => '../'

  target 'SampleFramework_Tests' do
    inherit! :search_paths

    post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

  end
end
